# Generated by Django 4.2.13 on 2024-05-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=256, verbose_name='发布会名称')),
                ('address', models.CharField(max_length=512, verbose_name='发布会地址')),
                ('limits', models.IntegerField(default=100)),
                ('status', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
